### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by kie27** [TheJackiMonster/HuionGT191LinuxDriver#4]
thanks for your work, 
I am trying to get this to work on deblan - I am not a C programmer, so it is all a struggle.
I added the following to fix errors that I was getting...
```
typedef unsigned int uint;
typedef unsigned short ushort;

```
but compiling on debian with gcc I get the following warnings and errors... 

```
$ gcc main.c huion-gt191.c -Wall -ansi -g -std=c99 -lX11 -lglfw -lusb -o output

huion-gt191.c: In function ‘findHuionGT191Device’:
huion-gt191.c:103:36: warning: operation on ‘off’ may be undefined [-Wsequence-point]
       result.maxX = (uint) (buf[off++] & 0xFF) | ((buf[off++] & 0xFF) << 8);
                                 ~~~^~
huion-gt191.c:104:36: warning: operation on ‘off’ may be undefined [-Wsequence-point]
       result.maxY = (uint) (buf[off++] & 0xFF) | ((buf[off++] & 0xFF) << 8);
                                 ~~~^~
huion-gt191.c:105:43: warning: operation on ‘off’ may be undefined [-Wsequence-point]
       result.maxPressure = (uint) (buf[off++] & 0xFF) | ((buf[off++] & 0xFF) << 8);
                                        ~~~^~
huion-gt191.c:106:42: warning: operation on ‘off’ may be undefined [-Wsequence-point]
       result.resolution = (uint) (buf[off++] & 0xFF) | ((buf[off++] & 0xFF) << 8);
                                       ~~~^~
huion-gt191.c:111:59: warning: operation on ‘off’ may be undefined [-Wsequence-point]
       result.maxX = (uint) (buf[off++] & 0xFF) | ((buf[off++] & 0xFF) << 8) | ((buf[off++] & 0xFF) << 16);
                                                        ~~~^~
huion-gt191.c:111:59: warning: operation on ‘off’ may be undefined [-Wsequence-point]
huion-gt191.c:112:59: warning: operation on ‘off’ may be undefined [-Wsequence-point]
       result.maxY = (uint) (buf[off++] & 0xFF) | ((buf[off++] & 0xFF) << 8) | ((buf[off++] & 0xFF) << 16);
                                                        ~~~^~
huion-gt191.c:112:59: warning: operation on ‘off’ may be undefined [-Wsequence-point]
huion-gt191.c:113:43: warning: operation on ‘off’ may be undefined [-Wsequence-point]
       result.maxPressure = (uint) (buf[off++] & 0xFF) | ((buf[off++] & 0xFF) << 8);
                                        ~~~^~
huion-gt191.c:114:42: warning: operation on ‘off’ may be undefined [-Wsequence-point]
       result.resolution = (uint) (buf[off++] & 0xFF) | ((buf[off++] & 0xFF) << 8);
                                       ~~~^~
/usr/bin/ld: /tmp/ccUV9lkb.o: undefined reference to symbol 'XRRGetOutputProperty'
//usr/lib/x86_64-linux-gnu/libXrandr.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

```

any help would be appreciated.

**Comment by TheJackiMonster** [comment]
No problem.. you are just missing one library 'libXrandr'...

`gcc main.c huion-gt191.c -Wall -ansi -g -std=c99 -lX11 -lglfw -lusb -lXrandr -o output`

This should work, but I would recommend to use 'cmake' to compile... I will reorganize the source soon and add a little things.. so compiling manually from terminal will become a little messy...

**Comment by TheJackiMonster** [comment]
I uploaded the never source and a script which you can use to compile (using cmake but removing all generated files from it afterwards except the executable)... that should solve it.

**Comment by kie27** [comment]
Sorry for my newbie questions... adding libXrandr fixed the compilation problem :)

I also tried cmake although I had to change the minimum version to 3.7 to match my installed version on debian.

I also copied the `huion-tablet.conf` file to `/usr/share/X11/xorg.conf.d/50-huion.conf`
and `huion-gt191.rules` to `/lib/udev/68-huion-gt191.rules`

In the settings editor for Xfconf I see that kamvas-pen is listed in the pointers channel

lsusb - I think the entry is this one...
`Bus 001 Device 004: ID 256c:006e  `
no name is listed.

In dmesg I see the lines :
```
input: Huion GT191 as /devices/virtual/input/input26
usb 1-14: usbfs: process 3196 (HuionGT191Linux) did not claim interface 0 before use
```

I run the driver binary `./HuionGT191LinuxDriver` as root,
but am not sure of how I should now proceed to actually get the tablet working e.g. with krita or gimp

Any help gratefully appreciated.

**Comment by TheJackiMonster** [comment]
After running the driver it should actually match all events from the usb-connection to the xinput-device in linux. So actually Krita, Gimp etc. should recognize the device and its input. It can be the case, that you need to look up the software's configuration for input devices and enable it there, for example Gimp didn't recognized it from the beginning until I changed something in its config on my host.

Also it can be the case that a software won't receive any events from the device if you have started it before running the driver, the order can be important. I would recommend to test it in the beginning with the program 'xournal' which hadn't needed any necessary configurations.. just run the driver, then start it -> It should actually work.

**Comment by kie27** [comment]
It's working!!! thank you very much.

Couldn't get it to work... so I started again, with a new clone from git.
Changed cmake to 3.7 to match my system.
Compile script works perfectly.
```
$ ./compile.sh 
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kie/git/HuionGT191LinuxDriver
Scanning dependencies of target Driver
[ 20%] Building C object CMakeFiles/Driver.dir/src/Device.c.o
[ 40%] Building C object CMakeFiles/Driver.dir/src/Driver.c.o
[ 60%] Building C object CMakeFiles/Driver.dir/src/Handle.c.o
[ 80%] Building C object CMakeFiles/Driver.dir/src/Monitor.c.o
[100%] Linking C executable Driver
[100%] Built target Driver

```
but install script gives me some errors.
$ ./install.sh 
```
./install.sh: 4: ./install.sh: !=: not found
./install.sh: 14: ./install.sh: [[: not found
./install.sh: 20: ./install.sh: [[: not found
Rules for udev are installed now...
./install.sh: 29: ./install.sh: [[: not found
./install.sh: 33: ./install.sh: arithmetic expression: expecting EOF: "01~+1"
```
but running the driver everything is working. Thanks so much for your help.

**Comment by TheJackiMonster** [comment]
Ok, good to see that. ^^

I guess I mixed some bash syntax with shell and others.. will come on my todo-list.
