### ISSUE TITLE
Krita doesn't recognizes the device as tablet

### ISSUE THREAD

**Issue by TheJackiMonster** [TheJackiMonster/HuionGT191LinuxDriver#5]
I looked on the debugging messages of Krita and in parts of its source. I couldn't find a solution for this problem, but I think Krita thinks of the device as a general mouse cursor which is wrong.

Gimp, Xournal and MyPaint don't have this problem... the pressure works fine! Gimp and MyPaint even show with different icons or type names in the settings that they recognize it correctly.

(in MyPaint the Huion tablet is under the type 'Touchscreen' and my Wacom tablet under 'Touchpad', 'tablet-pad' and 'Pen'... maybe I can correct this [in Krita], if the Huion tablet is noticed as 'Pen' too)

**Comment by scurest** [comment]
@TheJackiMonster Thanks a ton for this driver! It's the only one that worked for me.

I poked around in Qt a little and they seem to detect a tablet by the presence of certain strings in the device name (`pen` and `stylus` work) so I changed

https://github.com/TheJackiMonster/HuionGT191LinuxDriver/blob/8951b78b50e04dab92ad6368b3c51e9524d25dc2/src/Handle.c#L116

to set the name to `"Huion GT191 pen"` and pressure started working in Krita!

I do get a spurious(?) error message for `unable to find device HUION_M168_171103` (the old name) now though.

**Comment by TheJackiMonster** [comment]
I tested the last change and it works now. The area to draw in Krita was surprisingly fitting to the current calibration values on my system. I should focus on that calibration again. I got a few new ideas to make it more accurate. At least this is closed now. ^_^
